description: "My prompt evaluation"

providers:
  - openai:gpt-4
  - openai:gpt-3.5-turbo

prompts:
  - "You are a helpful assistant. {{question}}"
  - "Answer this question concisely: {{question}}"

tests:
  - vars:
      question: "What is the capital of France?"
    assert:
      - type: contains
        value: "Paris"
  - vars:
      question: "Explain photosynthesis"
    assert:
      - type: contains
        value: "sunlight"
